In [2]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("/Users/ayaxdiaz/Desktop/uscities.csv")

In [6]:
data

                   STATE  ID
0               New York  NY
1             California  CA
2               Illinois  IL
3                Florida  FL
4                  Texas  TX
5           Pennsylvania  PA
6                Georgia  GA
7   District of Columbia  DC
8          Massachusetts  MA
9                Arizona  AZ
10            Washington  WA
11              Michigan  MI
12             Minnesota  MN
13              Colorado  CO
14              Maryland  MD
15                Nevada  NV
16                Oregon  OR
17              Missouri  MO
18                  Ohio  OH
19               Indiana  IN
20        North Carolina  NC
21              Virginia  VA
22             Wisconsin  WI
23          Rhode Island  RI
24                  Utah  UT
25             Tennessee  TN
26             Louisiana  LA
27              Kentucky  KY
28              Oklahoma  OK
29           Connecticut  CT
30              Nebraska  NE
31                Hawaii  HI
32            New Mexico  NM
33               Alabama  AL
34        South Carolina  SC
35                Kansas  KS
36                  Iowa  IA
37              Arkansas  AR
38                 Idaho  ID
39           Mississippi  MS
40           Puerto Rico  PR
41            New Jersey  NJ
42                Alaska  AK
43         New Hampshire  NH
44          North Dakota  ND
45                 Maine  ME
46          South Dakota  SD
47         West Virginia  WV
48               Montana  MT
49              Delaware  DE
50               Vermont  VT
51               Wyoming  WY

In [7]:
L_Data = data.STATE.str.lower()

In [8]:
L_Data

0                 new york
1               california
2                 illinois
3                  florida
4                    texas
5             pennsylvania
6                  georgia
7     district of columbia
8            massachusetts
9                  arizona
10              washington
11                michigan
12               minnesota
13                colorado
14                maryland
15                  nevada
16                  oregon
17                missouri
18                    ohio
19                 indiana
20          north carolina
21                virginia
22               wisconsin
23            rhode island
24                    utah
25               tennessee
26               louisiana
27                kentucky
28                oklahoma
29             connecticut
30                nebraska
31                  hawaii
32              new mexico
33                 alabama
34          south carolina
35                  kansas
36                    iowa
37                arkansas
38                   idaho
39             mississippi
40             puerto rico
41              new jersey
42                  alaska
43           new hampshire
44            north dakota
45                   maine
46            south dakota
47           west virginia
48                 montana
49                delaware
50                 vermont
51                 wyoming
Name: STATE, dtype: object

In [9]:
U_Data = data.STATE.str.upper()

In [10]:
U_Data

0                 NEW YORK
1               CALIFORNIA
2                 ILLINOIS
3                  FLORIDA
4                    TEXAS
5             PENNSYLVANIA
6                  GEORGIA
7     DISTRICT OF COLUMBIA
8            MASSACHUSETTS
9                  ARIZONA
10              WASHINGTON
11                MICHIGAN
12               MINNESOTA
13                COLORADO
14                MARYLAND
15                  NEVADA
16                  OREGON
17                MISSOURI
18                    OHIO
19                 INDIANA
20          NORTH CAROLINA
21                VIRGINIA
22               WISCONSIN
23            RHODE ISLAND
24                    UTAH
25               TENNESSEE
26               LOUISIANA
27                KENTUCKY
28                OKLAHOMA
29             CONNECTICUT
30                NEBRASKA
31                  HAWAII
32              NEW MEXICO
33                 ALABAMA
34          SOUTH CAROLINA
35                  KANSAS
36                    IOWA
37                ARKANSAS
38                   IDAHO
39             MISSISSIPPI
40             PUERTO RICO
41              NEW JERSEY
42                  ALASKA
43           NEW HAMPSHIRE
44            NORTH DAKOTA
45                   MAINE
46            SOUTH DAKOTA
47           WEST VIRGINIA
48                 MONTANA
49                DELAWARE
50                 VERMONT
51                 WYOMING
Name: STATE, dtype: object

In [11]:
L_Data.to_csv("/Users/ayaxdiaz/Desktop/L_Data.csv")

In [12]:
U_Data.to_csv("/Users/ayaxdiaz/Desktop/U_Data.csv")